spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/explore?autoReconnect=true&useSSL=false
    username: exploreuser
    password: secret!
    driver-class-name: com.mysql.jdbc.Driver
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    useLocalTransactionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
server:
  port: 8100
logging:
  file: explore.log
